version: "3.7"

services:
  slim:
    build: ./phpapp
    container_name: slim
    restart: always
    expose:
      - 8000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
